import LeftSidebar from "@/components/LeftSidebar";
import MobileNav from "@/components/MobileNav";
import type { Metadata } from "next";
import Image from "next/image";
import { Toaster } from "@/components/ui/toaster";
import AudioPlayer from "@/components/AudioPlayer";
import Footer from "@/components/Footer";
import Nav from "@/components/Nav";
import CreditsBanner from "@/components/CreditsBanner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col h-auto">
      <main className="relative flex ">
        <section className="flex min-h-screen flex-1 flex-col bg-white-1">
          <div className="block md:hidden">
            <MobileNav />
          </div>
          <Nav />
          <CreditsBanner />
          <Toaster />

          {children}
          <Footer />
        </section>
      </main>
      <AudioPlayer />
    </div>
  );
}
